<a href="https://colab.research.google.com/github/ZhRaF/Ai-training/blob/master/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import pandas as pd
import os

# merging 1 year sales
files = [file for file in os.listdir('./') if file.endswith('.csv')]
# this returns file names

# List to store DataFrames
dfs = []

for file in files:
   df = pd.read_csv('./' + file)
  # creating a df from each  file path
   dfs.append(df)


# Concatenate all DataFrames in the list
all_months_data = pd.concat(dfs, ignore_index=True)
# all_months_data.head()

all_months_data.to_csv("year_sales.csv",index=False)

# reading from our file
print("year sales")
year_sales=pd.read_csv("year_sales.csv")
# year_sales.head()

ValueError: No objects to concatenate

In [ ]:
# data cleaning to get rid of nan valus
nan_df=year_sales[year_sales.isna().any(axis=1)]
# rows that any of their columns are NaN
# axis=1 for checking rows , 0 for columns

# how many nan values are there ?!!
print(len(nan_df))

# how many rows with all culumns are nan values are there ?!!
print(len(year_sales[year_sales.isna().all(axis=1)]))

# deleting them
year_sales=year_sales.dropna(how='all')
nan_df.head()

0
0

ValueError: invalid literal for int() with base 10: 'Or'

In [ ]:
Or_values=year_sales[year_sales['Order Date'].str[0:2] == 'Or']
print(len(Or_values))
# how many rows with Or in date field


year_sales=year_sales[year_sales['Order Date'].str[0:2] != 'Or']
# deleting them

3195

In [ ]:
# BEST MONTH FOR SALES
# 1ST METHOD

# ADDING MONTH COLUMN
year_sales['month']=year_sales['Order Date'].str[0:2].astype(int)
year_sales.head()

total_price = 0
max_month = 0
max_price = 0

for i in range(1, 13):
    month_sales = year_sales[year_sales['month'] == i]
    order_price = month_sales['Quantity Ordered'].astype(float) * month_sales['Price Each'].astype(float)

    price_month = order_price.sum()
    print(price_month)

    if price_month > max_price:
        max_price = price_month
        max_month = i

print("Month with the maximum sales:", max_month)
print("Total price in that month:", max_price)

16400310.569999997
19818201.779999997
25263903.419999994
30516032.159999996
28373460.749999993
23200220.340000004
23829981.839999992
20200210.91999999
18878041.169999998
33630541.92
28796428.8
41520990.059999995
Month with the maximum sales: 12
Total price in that month: 41520990.059999995

In [ ]:
# BEST MONTH FOR SALES
# 2ND METHOD
year_sales['sales'] = year_sales['Quantity Ordered'].astype(float) * year_sales['Price Each'].astype(float)
year_sales.groupby('month').sum()

<ipython-input-64-841f21478c77>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  year_sales.groupby('month').sum()

             sales
month
1      16400310.57
2      19818201.78
3      25263903.42
4      30516032.16
5      28373460.75
6      23200220.34
7      23829981.84
8      20200210.92
9      18878041.17
10     33630541.92
11     28796428.80
12     41520990.06